version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - DJANGO_SETTINGS_MODULE=fc_backend_v2.settings
      - SECRET_KEY=${SECRET_KEY}
      - AZURE_POSTGRESQL_NAME=${AZURE_POSTGRESQL_NAME}
      - AZURE_POSTGRESQL_HOST=${AZURE_POSTGRESQL_HOST}
      - AZURE_POSTGRESQL_USER=${AZURE_POSTGRESQL_USER}
      - AZURE_POSTGRESQL_PASSWORD=${AZURE_POSTGRESQL_PASSWORD}
      - AZURE_REDIS_CONNECTIONSTRING=${AZURE_REDIS_CONNECTIONSTRING}
      - CACHELOCATION=${CACHELOCATION}
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${AZURE_POSTGRESQL_NAME}
      POSTGRES_USER: ${AZURE_POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${AZURE_POSTGRESQL_PASSWORD}

  redis:
    image: redis
    restart: unless-stopped

volumes:
  postgres-data:
